// <auto-generated />
namespace Project.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class eProjectDb_lastv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eProjectDb_lastv5));
        
        string IMigrationMetadata.Id
        {
            get { return "202103141301483_eProjectDb_last-v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
